[package]
name = "infer_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "infer_server"
path = "src/lib.rs"

[dependencies]
axum = { version = "0.5.16", features = ["multipart", "query"] }
dirs = "4.0.0"
env_logger = "0.9.1"
futures = "0.3.24"
image = "0.24.4"
log = "0.4.17"
ndarray = "0.15.6"
reqwest = { version = "0.11.12", features = ["stream"] }
serde = { version = "1.0.145", features = ["derive"] }
smallvec = "1.10.0"
tokio = { version = "1.21.2", features = ["full"] }
tract-onnx = "0.18.0"
