name: CI Workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install library for rscam
        run: apt update && apt install -y libv4l-dev
      - name: Download onnx models
        run: |
          wget https://github.com/onnx/models/raw/master/vision/body_analysis/ultraface/models/version-RFB-320.onnx
          wget https://github.com/onnx/models/raw/master/vision/body_analysis/ultraface/models/version-RFB-640.onnx
      - name: Run tests
        run: cargo test -- --skip test_saving_frames

  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install library for rscam
        run: apt update && apt install -y libv4l-dev

      - name: Set variables
        run: |
          echo "TIMESTAMP=$(date +'%Y-%m-%d_%H:%M:%S')" >> $GITHUB_ENV
          echo "RELEASE_FILE=infercam_onnx_${GITHUB_REF#refs/tags/}.tar.gz" >> $GITHUB_ENV

      - name: Build in release mode
        run: cargo build --release
      - name: List build content
        run: ls -la
 
      - name: Compress release files
        run: tar -czf ${RELEASE_FILE} target/release/infercam* target/release/lib*
        if: startsWith(github.ref, 'refs/tags/')
      - name: Publish a release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@69a9b03fd9694e185b5d1450f1c534fb50ed4ab8
        with:
          files: |
            *.tar.gz
